//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTSPensjon.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PTSPensjon.Resx.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string IntroPage_1_desc {
            get {
                return ResourceManager.GetString("IntroPage_1_desc", resourceCulture);
            }
        }
        
        public static string IntroPage_2_desc {
            get {
                return ResourceManager.GetString("IntroPage_2_desc", resourceCulture);
            }
        }
        
        public static string IntroPage_3_desc {
            get {
                return ResourceManager.GetString("IntroPage_3_desc", resourceCulture);
            }
        }
        
        public static string IntroPage_4_desc {
            get {
                return ResourceManager.GetString("IntroPage_4_desc", resourceCulture);
            }
        }
        
        public static string IntroPage_5_desc {
            get {
                return ResourceManager.GetString("IntroPage_5_desc", resourceCulture);
            }
        }
        
        public static string IntroPage_5_video_path {
            get {
                return ResourceManager.GetString("IntroPage_5_video_path", resourceCulture);
            }
        }
        
        public static string IntroPages_skip_intro {
            get {
                return ResourceManager.GetString("IntroPages_skip_intro", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_Messages {
            get {
                return ResourceManager.GetString("HomeMenuItem_Messages", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_Seatime {
            get {
                return ResourceManager.GetString("HomeMenuItem_Seatime", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_ApplyPension {
            get {
                return ResourceManager.GetString("HomeMenuItem_ApplyPension", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_News {
            get {
                return ResourceManager.GetString("HomeMenuItem_News", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_Calculator {
            get {
                return ResourceManager.GetString("HomeMenuItem_Calculator", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_Rules {
            get {
                return ResourceManager.GetString("HomeMenuItem_Rules", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_Help {
            get {
                return ResourceManager.GetString("HomeMenuItem_Help", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_Settings {
            get {
                return ResourceManager.GetString("HomeMenuItem_Settings", resourceCulture);
            }
        }
        
        public static string HomeMenuItem_About {
            get {
                return ResourceManager.GetString("HomeMenuItem_About", resourceCulture);
            }
        }
        
        public static string Calculator_header {
            get {
                return ResourceManager.GetString("Calculator_header", resourceCulture);
            }
        }
        
        public static string Calculator_desc {
            get {
                return ResourceManager.GetString("Calculator_desc", resourceCulture);
            }
        }
        
        public static string Calculator_field1 {
            get {
                return ResourceManager.GetString("Calculator_field1", resourceCulture);
            }
        }
        
        public static string Calculator_field2 {
            get {
                return ResourceManager.GetString("Calculator_field2", resourceCulture);
            }
        }
        
        public static string Calculator_field3 {
            get {
                return ResourceManager.GetString("Calculator_field3", resourceCulture);
            }
        }
        
        public static string Calculator_field4 {
            get {
                return ResourceManager.GetString("Calculator_field4", resourceCulture);
            }
        }
        
        public static string Calculator_field5 {
            get {
                return ResourceManager.GetString("Calculator_field5", resourceCulture);
            }
        }
        
        public static string Calculator_calculate_button {
            get {
                return ResourceManager.GetString("Calculator_calculate_button", resourceCulture);
            }
        }
        
        public static string Calculator_error_title {
            get {
                return ResourceManager.GetString("Calculator_error_title", resourceCulture);
            }
        }
        
        public static string Calculator_error_desc {
            get {
                return ResourceManager.GetString("Calculator_error_desc", resourceCulture);
            }
        }
        
        public static string Calculator_error_close {
            get {
                return ResourceManager.GetString("Calculator_error_close", resourceCulture);
            }
        }
        
        public static string CalcResult_title {
            get {
                return ResourceManager.GetString("CalcResult_title", resourceCulture);
            }
        }
        
        public static string CalcResult_header {
            get {
                return ResourceManager.GetString("CalcResult_header", resourceCulture);
            }
        }
        
        public static string CalcResult_field1 {
            get {
                return ResourceManager.GetString("CalcResult_field1", resourceCulture);
            }
        }
        
        public static string CalcResult_field2 {
            get {
                return ResourceManager.GetString("CalcResult_field2", resourceCulture);
            }
        }
        
        public static string CalcResult_field3 {
            get {
                return ResourceManager.GetString("CalcResult_field3", resourceCulture);
            }
        }
        
        public static string Rules_title {
            get {
                return ResourceManager.GetString("Rules_title", resourceCulture);
            }
        }
        
        public static string Rules_desc {
            get {
                return ResourceManager.GetString("Rules_desc", resourceCulture);
            }
        }
        
        public static string Rules_header1 {
            get {
                return ResourceManager.GetString("Rules_header1", resourceCulture);
            }
        }
        
        public static string Rules_desc1 {
            get {
                return ResourceManager.GetString("Rules_desc1", resourceCulture);
            }
        }
        
        public static string Rules_header2 {
            get {
                return ResourceManager.GetString("Rules_header2", resourceCulture);
            }
        }
        
        public static string Rules_desc2 {
            get {
                return ResourceManager.GetString("Rules_desc2", resourceCulture);
            }
        }
        
        public static string Rules_header3 {
            get {
                return ResourceManager.GetString("Rules_header3", resourceCulture);
            }
        }
        
        public static string Rules_desc3 {
            get {
                return ResourceManager.GetString("Rules_desc3", resourceCulture);
            }
        }
        
        public static string Help_FAQ_title {
            get {
                return ResourceManager.GetString("Help_FAQ_title", resourceCulture);
            }
        }
        
        public static string Help_email {
            get {
                return ResourceManager.GetString("Help_email", resourceCulture);
            }
        }
        
        public static string Help_callus {
            get {
                return ResourceManager.GetString("Help_callus", resourceCulture);
            }
        }
        
        public static string Help_calltimes_winter {
            get {
                return ResourceManager.GetString("Help_calltimes_winter", resourceCulture);
            }
        }
        
        public static string Help_calltimes_summer {
            get {
                return ResourceManager.GetString("Help_calltimes_summer", resourceCulture);
            }
        }
        
        public static string Help_chat {
            get {
                return ResourceManager.GetString("Help_chat", resourceCulture);
            }
        }
        
        public static string FAQ_title {
            get {
                return ResourceManager.GetString("FAQ_title", resourceCulture);
            }
        }
        
        public static string FAQ_link {
            get {
                return ResourceManager.GetString("FAQ_link", resourceCulture);
            }
        }
        
        public static string FAQ_link_local {
            get {
                return ResourceManager.GetString("FAQ_link_local", resourceCulture);
            }
        }
        
        public static string Settings_language_title {
            get {
                return ResourceManager.GetString("Settings_language_title", resourceCulture);
            }
        }
        
        public static string Settings_language_norwegian {
            get {
                return ResourceManager.GetString("Settings_language_norwegian", resourceCulture);
            }
        }
        
        public static string Settings_language_english {
            get {
                return ResourceManager.GetString("Settings_language_english", resourceCulture);
            }
        }
        
        public static string Settings_fontsize_title {
            get {
                return ResourceManager.GetString("Settings_fontsize_title", resourceCulture);
            }
        }
        
        public static string Settings_fontsize_small {
            get {
                return ResourceManager.GetString("Settings_fontsize_small", resourceCulture);
            }
        }
        
        public static string Settings_fontsize_medium {
            get {
                return ResourceManager.GetString("Settings_fontsize_medium", resourceCulture);
            }
        }
        
        public static string Settings_fontsize_large {
            get {
                return ResourceManager.GetString("Settings_fontsize_large", resourceCulture);
            }
        }
        
        public static string Settings_sound_title {
            get {
                return ResourceManager.GetString("Settings_sound_title", resourceCulture);
            }
        }
        
        public static string Settings_sound_desc {
            get {
                return ResourceManager.GetString("Settings_sound_desc", resourceCulture);
            }
        }
        
        public static string Settings_watchintro {
            get {
                return ResourceManager.GetString("Settings_watchintro", resourceCulture);
            }
        }
        
        public static string Settings_about_title {
            get {
                return ResourceManager.GetString("Settings_about_title", resourceCulture);
            }
        }
        
        public static string Settings_about_desc {
            get {
                return ResourceManager.GetString("Settings_about_desc", resourceCulture);
            }
        }
        
        public static string Settings_push_notifications_title {
            get {
                return ResourceManager.GetString("Settings_push_notifications_title", resourceCulture);
            }
        }
        
        public static string Settings_push_notifications_enabled {
            get {
                return ResourceManager.GetString("Settings_push_notifications_enabled", resourceCulture);
            }
        }
        
        public static string Settings_push_notifications_expired {
            get {
                return ResourceManager.GetString("Settings_push_notifications_expired", resourceCulture);
            }
        }
        
        public static string Settings_push_notifications_disabled_title {
            get {
                return ResourceManager.GetString("Settings_push_notifications_disabled_title", resourceCulture);
            }
        }
        
        public static string Settings_push_notifications_disabled_desc {
            get {
                return ResourceManager.GetString("Settings_push_notifications_disabled_desc", resourceCulture);
            }
        }
        
        public static string Settings_push_notifications_expired_desc {
            get {
                return ResourceManager.GetString("Settings_push_notifications_expired_desc", resourceCulture);
            }
        }
        
        public static string About_header1 {
            get {
                return ResourceManager.GetString("About_header1", resourceCulture);
            }
        }
        
        public static string About_desc1 {
            get {
                return ResourceManager.GetString("About_desc1", resourceCulture);
            }
        }
        
        public static string About_header2 {
            get {
                return ResourceManager.GetString("About_header2", resourceCulture);
            }
        }
        
        public static string About_desc2 {
            get {
                return ResourceManager.GetString("About_desc2", resourceCulture);
            }
        }
        
        public static string About_postbox {
            get {
                return ResourceManager.GetString("About_postbox", resourceCulture);
            }
        }
        
        public static string About_telephone {
            get {
                return ResourceManager.GetString("About_telephone", resourceCulture);
            }
        }
        
        public static string About_email {
            get {
                return ResourceManager.GetString("About_email", resourceCulture);
            }
        }
        
        public static string Push_notification_title {
            get {
                return ResourceManager.GetString("Push_notification_title", resourceCulture);
            }
        }
        
        public static string Push_notification_desc {
            get {
                return ResourceManager.GetString("Push_notification_desc", resourceCulture);
            }
        }
        
        public static string Push_notification_accept {
            get {
                return ResourceManager.GetString("Push_notification_accept", resourceCulture);
            }
        }
        
        public static string Push_notification_cancel {
            get {
                return ResourceManager.GetString("Push_notification_cancel", resourceCulture);
            }
        }
        
        public static string Push_notification_local_title {
            get {
                return ResourceManager.GetString("Push_notification_local_title", resourceCulture);
            }
        }
        
        public static string Push_notification_local_desc {
            get {
                return ResourceManager.GetString("Push_notification_local_desc", resourceCulture);
            }
        }
        
        public static string Static_email {
            get {
                return ResourceManager.GetString("Static_email", resourceCulture);
            }
        }
        
        public static string Static_email_draft_title {
            get {
                return ResourceManager.GetString("Static_email_draft_title", resourceCulture);
            }
        }
        
        public static string Static_email_draft_body {
            get {
                return ResourceManager.GetString("Static_email_draft_body", resourceCulture);
            }
        }
        
        public static string Static_phone_number {
            get {
                return ResourceManager.GetString("Static_phone_number", resourceCulture);
            }
        }
        
        public static string Static_call_title {
            get {
                return ResourceManager.GetString("Static_call_title", resourceCulture);
            }
        }
        
        public static string Static_call_desc {
            get {
                return ResourceManager.GetString("Static_call_desc", resourceCulture);
            }
        }
        
        public static string Static_call_yes_action {
            get {
                return ResourceManager.GetString("Static_call_yes_action", resourceCulture);
            }
        }
        
        public static string Static_call_no_action {
            get {
                return ResourceManager.GetString("Static_call_no_action", resourceCulture);
            }
        }
        
        public static string Static_address {
            get {
                return ResourceManager.GetString("Static_address", resourceCulture);
            }
        }
        
        public static string Generic_internet_error_title {
            get {
                return ResourceManager.GetString("Generic_internet_error_title", resourceCulture);
            }
        }
        
        public static string Generic_internet_error_desc {
            get {
                return ResourceManager.GetString("Generic_internet_error_desc", resourceCulture);
            }
        }
        
        public static string Generic_internet_error_ok {
            get {
                return ResourceManager.GetString("Generic_internet_error_ok", resourceCulture);
            }
        }
    }
}
